export const COMPILER_SNIPPETS = [
  {
    id: 'starter',
    label: 'Starter template',
    description: 'Basic function + console output',
    code: [
      '// Write JavaScript and press Run (Ctrl/Cmd + Enter)',
      '',
      'function solve(input) {',
      "  return input.toUpperCase();",
      '}',
      '',
      "console.log(solve('hello'));",
    ].join('\n'),
  },
  {
    id: 'unit-tests',
    label: 'Unit tests (expect)',
    description: 'Built-in assertion helpers',
    code: [
      'function add(a, b) {',
      '  return a + b;',
      '}',
      '',
      'function isPalindrome(value) {',
      '  const normalized = value.toLowerCase().replace(/[^a-z0-9]/g, "");',
      '  return normalized === normalized.split("").reverse().join("");',
      '}',
      '',
      'expect(add(2, 3)).toBe(5);',
      'expect(add(-1, 1)).toEqual(0);',
      'expect(isPalindrome("Racecar")).toBeTruthy();',
      'expect(isPalindrome("node")).toContain("o");',
      '',
      'console.log("All assertions passed");',
    ].join('\n'),
  },
  {
    id: 'async-await',
    label: 'Async / await',
    description: 'Promises with async flow',
    code: [
      'const delay = (ms, value) => new Promise((resolve) => {',
      '  setTimeout(() => resolve(value), ms);',
      '});',
      '',
      'async function loadUser() {',
      '  console.time("loadUser");',
      '  const profile = await delay(120, { id: 1, name: "Ada" });',
      '  const permissions = await delay(80, ["read", "write"]);',
      '  console.timeEnd("loadUser");',
      '  return { ...profile, permissions };',
      '}',
      '',
      'loadUser().then(console.log);',
    ].join('\n'),
  },
  {
    id: 'array-pipeline',
    label: 'Array pipeline',
    description: 'map, filter, reduce chain',
    code: [
      'const orders = [',
      '  { id: 1, total: 42, status: "paid" },',
      '  { id: 2, total: 18, status: "pending" },',
      '  { id: 3, total: 75, status: "paid" },',
      '  { id: 4, total: 9, status: "cancelled" },',
      '];',
      '',
      'const paidRevenue = orders',
      '  .filter((order) => order.status === "paid")',
      '  .map((order) => order.total)',
      '  .reduce((sum, total) => sum + total, 0);',
      '',
      'console.table(orders);',
      'console.log("Paid revenue:", paidRevenue);',
    ].join('\n'),
  },
  {
    id: 'classes',
    label: 'ES6 classes',
    description: 'Inheritance and methods',
    code: [
      'class Shape {',
      '  constructor(name) {',
      '    this.name = name;',
      '  }',
      '  describe() {',
      '    return "Shape: " + this.name;',
      '  }',
      '}',
      '',
      'class Circle extends Shape {',
      '  constructor(radius) {',
      '    super("circle");',
      '    this.radius = radius;',
      '  }',
      '  area() {',
      '    return Math.PI * this.radius ** 2;',
      '  }',
      '}',
      '',
      'const c = new Circle(4);',
      'console.log(c.describe(), "area =", c.area().toFixed(2));',
    ].join('\n'),
  },
  {
    id: 'closures',
    label: 'Closures & memoize',
    description: 'Private state with closures',
    code: [
      'function createCounter(start = 0) {',
      '  let value = start;',
      '  return {',
      '    inc(step = 1) { value += step; return value; },',
      '    dec(step = 1) { value -= step; return value; },',
      '    read() { return value; },',
      '  };',
      '}',
      '',
      'const counter = createCounter(10);',
      'console.log(counter.inc());',
      'console.log(counter.inc(5));',
      'console.log(counter.dec(2));',
      'console.log(counter.read());',
    ].join('\n'),
  },
  {
    id: 'recursion',
    label: 'Recursion',
    description: 'Tree flatten with depth tracking',
    code: [
      'const tree = {',
      '  value: 1,',
      '  children: [',
      '    { value: 2, children: [{ value: 4, children: [] }] },',
      '    { value: 3, children: [] },',
      '  ],',
      '};',
      '',
      'function flatten(node, depth = 0, acc = []) {',
      '  acc.push({ value: node.value, depth });',
      '  for (const child of node.children) {',
      '    flatten(child, depth + 1, acc);',
      '  }',
      '  return acc;',
      '}',
      '',
      'console.table(flatten(tree));',
    ].join('\n'),
  },
  {
    id: 'destructuring',
    label: 'Destructuring & spread',
    description: 'Object/array patterns',
    code: [
      'const user = { id: 7, profile: { city: "Pune", role: "dev" }, tags: ["js", "react"] };',
      '',
      'const { id, profile: { city, ...profileRest }, tags: [primaryTag, ...otherTags] } = user;',
      'const cloned = { ...user, profile: { ...user.profile, country: "IN" } };',
      '',
      'console.log({ id, city, profileRest, primaryTag, otherTags });',
      'console.dir(cloned);',
    ].join('\n'),
  },
];

export const DEFAULT_SNIPPET_ID = 'starter';
